import React from "react";
import Card from "./Card";

const MenuData = [
    {
        id:1,
        cat:1,
        name: "Quesataco",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        price: "$3.75",
        urlImg: "",
    },
    {
        id:2,
        cat:1,
        name: "Quesabirria 3Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797511/imagen_2025-01-13_124509039_brs9qq.png",
    },
    {
        id:3,
        cat:1,
        name: "Asada fries",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "",
    },
    {
        id:4,
        cat:1,
        name: "Nachos",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797587/imagen_2025-01-13_124624619_ecprrp.png",
    },
    {
        id:5,
        cat:1,
        name: "Gorditas",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.99",
        urlImg: "",
    },
    {
        id:5,
        cat:1,
        name: "Sopes",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.99",
        urlImg: "",
    },
    {
        id:7,
        cat:1,
        name: "Tacos dorados",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$1.99",
        urlImg: "",
    },
    {
        id:8,
        cat:1,
        name: "Quesadilla",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "",
    },
    {
        id:9,
        cat:1,
        name: "Sopa ramen con birria",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "",
    },
    {
        id:10,
        cat:1,
        name: "Mulitas",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797560/imagen_2025-01-13_124557052_lcv8o2.png",
    },
    {
        id:11,
        cat:1,
        name: "Burrito Regular",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "",
    },
    {
        id:12,
        cat:1,
        name: "Burrito Supreme",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$11.99",
        urlImg: "",
    },
    {
        id:13,
        cat:1,
        name: "Burrito California",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "",
    },
    {
        id:14,
        cat:1,
        name: "Monster Chetos Burrito",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "",
    },
    {
        id:15,
        cat:1,
        name: "Breakfast Burrito",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "",
    },
    {
        id:16,
        cat:1,
        name: "Wet Burrito",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$11.99",
        urlImg: "",
    },
    {
        id:17,
        cat:1,
        name: "Torta regular",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.00",
        urlImg: "",
    },
    {
        id:18,
        cat:1,
        name: "Torta Especial",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.50",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797532/imagen_2025-01-13_124529184_b86gtd.png",
    },
    {
        id:19,
        cat:1,
        name: "Torta Cubana",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$11.50",
        urlImg: "",
    },
    {
        id:20,
        cat:2,
        name: "Molcajete",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$27.99",
        urlImg: "",
    },{
        id:21,
        cat:2,
        name: "Aguachile",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797847/imagen_2025-01-13_125044420_qqv2al.png",
    },
    {
        id:22,
        cat:2,
        name: "Torre de mariscos",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$24.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797742/imagen_2025-01-13_124859821_uuispi.png",
    },
    {
        id:23,
        cat:2,
        name: "Camarones a la diabla",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797917/imagen_2025-01-13_125153436_l4vqiv.png",
    },
    {
        id:24,
        cat:2,
        name: "Caldo de 7 mares",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$25.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797869/imagen_2025-01-13_125106627_yifp9t.png",
    },
    {
        id:25,
        cat:2,
        name: "Ostiones 12 Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$22.99",
        urlImg: "",
    },
    {
        id:26,
        cat:2,
        name: "Ostiones preparados 12 Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$27.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797718/WhatsApp_Image_2024-12-05_at_9.16.18_PM_jybpbq.jpg",
    },
    {
        id:27,
        cat:2,
        name: "Charola especial",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$45.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797893/imagen_2025-01-13_125129855_fxd6zi.png",
    },
    {
        id:28,
        cat:2,
        name: "Filete de pescado",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$18.99",
        urlImg: "",
    },
    {
        id:29,
        cat:2,
        name: "Mojarra",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$16.99",
        urlImg: "",
    },
    {
        id:30,
        cat:2,
        name: "Tacos de gobernador",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.50",
        urlImg: "",
    },
    {
        id:31,
        cat:2,
        name: "Caldo de camaron y pescado",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$21.99",
        urlImg: "",
    },
    {
        id:32,
        cat:2,
        name: "Coctel de camaron",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$16.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797794/imagen_2025-01-13_124950894_jkt7i9.png",
    },
    {
        id:33,
        cat:2,
        name: "Coctel de camaron y pulpo",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$17.99",
        urlImg: "",
    },
    {
        id:34,
        cat:2,
        name: "Tostada de ceviche de pescado",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$8.99",
        urlImg: "",
    },
    {
        id:35,
        cat:2,
        name: "Tostada de camaron",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$9.99",
        urlImg: "",
    },
    {
        id:36,
        cat:2,
        name: "Caldo de camaron",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "",
    },
    {
        id:37,
        cat:2,
        name: "Fajitas mixtas",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$27.99",
        urlImg: "",
    },
    {
        id:38,
        cat:3,
        name: "Hamburguesa regular",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$8.00",
        urlImg: "",
    },
    {
        id:39,
        cat:3,
        name: "Hamburguesa Doble carne",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$9.00",
        urlImg: "",
    },
    {
        id:40,
        cat:3,
        name: "Hamburguesa Especial",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.00",
        urlImg: "",
    },
    {
        id:41,
        cat:3,
        name: "Nuggets",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$8.99",
        urlImg: "",
    },
    {
        id:42,
        cat:4,
        name: "Agua fresca - mediana",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$3.00",
        urlImg: "",
    },
    {
        id:43,
        cat:4,
        name: "Agua fresca - grande",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.00",
        urlImg: "",
    },
    {
        id:44,
        cat:4,
        name: "Cerveza",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$5.00",
        urlImg: "",
    },
    {
        id:45,
        cat:4,
        name: "Michelada",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "",
    },
    {
        id:46,
        cat:4,
        name: "Michelada loca",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$14.99",
        urlImg: "",
    },
    {
        id:47,
        cat:5,
        name: "Menudo mediano",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797956/imagen_2025-01-13_125232710_rd6nye.png",
    },
    {
        id:48,
        cat:5,
        name: "Menudo grande",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$14.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797956/imagen_2025-01-13_125232710_rd6nye.png",
    },
    {
        id:49,
        cat:5,
        name: "Birria de chivo mediano",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$13.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797976/imagen_2025-01-13_125253085_pjckcx.png",
    },
    {
        id:50,
        cat:5,
        name: "Birria de chivo grande",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$15.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797976/imagen_2025-01-13_125253085_pjckcx.png",
    },  
]

const Menu = ({ selectedCategory }) => {
    const filteredData = MenuData.filter(item => item.cat === selectedCategory);

    return (
        <div className="bg-gray-100 py-10">
            <div className="container">
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                    {filteredData.length > 0 ? (
                        filteredData.map((item, index) => (
                            <Card key={index} {...item} />
                        ))
                    ) : (
                        <p></p>
                    )}
                </div>
            </div>
        </div>
    );
}

export default Menu;