const MenuData = [
    {
        id:1,
        cat:1,
        name: "Quesataco",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        price: "$3.75",
        urlImg: "https://www.aquiestexcoco.com/aet/wp-content/uploads/2016/08/texcoco-quesataco-IMG_6547.jpg",
    },
    {
        id:2,
        cat:1,
        name: "Quesabirria 3 Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797511/imagen_2025-01-13_124509039_brs9qq.png",
    },
    {
        id:3,
        cat:1,
        name: "Asada fries",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736971968/imagen_2025-01-15_131244557_l9d5tr.png",
    },
    {
        id:4,
        cat:1,
        name: "Nachos",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797587/imagen_2025-01-13_124624619_ecprrp.png",
    },
    {
        id:5,
        cat:1,
        name: "Gorditas",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$5.99",
        urlImg: "https://hips.hearstapps.com/hmg-prod/images/gorditas-1-1676665006.jpg?crop=1xw:0.843558282208589xh;center,top&resize=1200:*",
    },
    {
        id:5,
        cat:1,
        name: "Sopes",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$5.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736971932/imagen_2025-01-15_131208769_cqyb0u.png",
    },
    {
        id:7,
        cat:1,
        name: "Tacos dorados",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$1.99",
        urlImg: "https://i.ytimg.com/vi/cNFMSlHvdDk/maxresdefault.jpg",
    },
    {
        id:8,
        cat:1,
        name: "Quesadilla",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://www.vvsupremo.com/wp-content/uploads/2015/11/900X570_Two-Cheese-Quesadillas.jpg",
    },
    {
        id:9,
        cat:1,
        name: "Sopa ramen con birria",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://inmamamaggieskitchen.com/wp-content/uploads/2021/02/Birria-Ramen.jpg",
    },
    {
        id:10,
        cat:1,
        name: "Mulitas",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797560/imagen_2025-01-13_124557052_lcv8o2.png",
    },
    {
        id:11,
        cat:1,
        name: "Burrito Regular",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740807493/imagen_2025-02-28_223809063_kiva2e.png",
    },
    {
        id:12,
        cat:1,
        name: "Burrito Supreme",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$11.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740807493/imagen_2025-02-28_223809063_kiva2e.png",
    },
    {
        id:13,
        cat:1,
        name: "Burrito California",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736973324/imagen_2025-01-15_133517091_joo1py.png",
    },
    {
        id:14,
        cat:1,
        name: "Monster Chettos Burrito",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736973274/imagen_2025-01-15_133427719_nkufe6.png",
    },
    {
        id:15,
        cat:1,
        name: "Breakfast Burrito",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736972902/imagen_2025-01-15_132817377_xijeg9.png",
    },
    {
        id:16,
        cat:1,
        name: "Wet Burrito",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$11.99",
        urlImg: "https://cdn.grmag.com/wp-content/uploads/sites/113/2023/10/Burrito-363.jpg",
    },
    {
        id:17,
        cat:1,
        name: "Torta regular",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.00",
        urlImg: "https://www.lagula.com.mx/wp-content/uploads/2024/05/torta-mexicana.jpg",
    },
    {
        id:18,
        cat:1,
        name: "Torta Especial",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.50",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736971808/imagen_2025-01-15_131004076_sxhpgl.png",
    },
    {
        id:19,
        cat:1,
        name: "Torta Cubana",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$11.50",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797532/imagen_2025-01-13_124529184_b86gtd.png",
    },
    {
        id:20,
        cat:2,
        name: "Molcajete",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$27.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740804217/imagen_2025-02-28_214335332_kkpjye.png",
    },{
        id:21,
        cat:2,
        name: "Aguachile",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797847/imagen_2025-01-13_125044420_qqv2al.png",
    },
    {
        id:22,
        cat:2,
        name: "Torre de mariscos",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$24.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797742/imagen_2025-01-13_124859821_uuispi.png",
    },
    {
        id:23,
        cat:2,
        name: "Camarones a la diabla",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797917/imagen_2025-01-13_125153436_l4vqiv.png",
    },
    {
        id:24,
        cat:2,
        name: "Caldo de 7 mares",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$25.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797869/imagen_2025-01-13_125106627_yifp9t.png",
    },
    {
        id:25,
        cat:2,
        name: "Ostiones 12 Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$22.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797718/WhatsApp_Image_2024-12-05_at_9.16.18_PM_jybpbq.jpg",
    },
    {
        id:26,
        cat:2,
        name: "Ostiones preparados 12 Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$27.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797718/WhatsApp_Image_2024-12-05_at_9.16.18_PM_jybpbq.jpg",
    },
    {
        id:27,
        cat:2,
        name: "Charola especial",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$45.00",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740814000/imagen_2025-03-01_002637809_qlpdx8.png",
    },
    {
        id:28,
        cat:2,
        name: "Filete de pescado",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$18.99",
        urlImg: "https://www.cocinadelirante.com/800x600/filters:format(webp):quality(75)/sites/default/files/images/2022/12/como-cocinar-filete-pescado-no-se-pegue.jpg",
    },
    {
        id:29,
        cat:2,
        name: "Mojarra",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$17.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740814088/mojarra_docgze.png",
    },
    {
        id:30,
        cat:2,
        name: "Tacos de gobernador",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.50",
        urlImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4mpVPWUoq_b6i5wo7-_QCFX1cKjZBAxdPZw&s",
    },
    {
        id:31,
        cat:2,
        name: "Caldo de camaron y pescado",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$21.99",
        urlImg: "https://i.ytimg.com/vi/m_o9-4bnG8A/maxresdefault.jpg",
    },
    {
        id:32,
        cat:2,
        name: "Coctel de camaron",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$16.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797794/imagen_2025-01-13_124950894_jkt7i9.png",
    },
    {
        id:33,
        cat:2,
        name: "Coctel de camaron y pulpo",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$17.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740808395/imagen_2025-02-28_225312549_uxhy9z.png",
    },
    {
        id:34,
        cat:2,
        name: "Tostada de ceviche de pescado",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$8.99",
        urlImg: "https://mariscoselrey.com.mx/wp-content/uploads/2020/03/Cev.-de-Pescado.jpg",
    },
    {
        id:35,
        cat:2,
        name: "Tostada de camaron",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$9.99",
        urlImg: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiYfn8ZX7_X1iT0umcFtIFqcrRG_MSoGp5lPpUfpWWkqu2-QsbIFQSgEGuGeOJEG9lCVu-vaQ5Y7dBmXYcqzVik-4ntx2YmBusImCqWe7IdZBsiOApOYKR70_SUGJrTHmXVLswx_PyX7Tw/s1600/DSC09147.JPG",
    },
    {
        id:36,
        cat:2,
        name: "Caldo de camaron",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$21.99",
        urlImg: "https://i.pinimg.com/736x/25/4d/25/254d256bac7619605086edadb113165e.jpg",
    },
    {
        id:37,
        cat:2,
        name: "Fajitas mixtas",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$27.99",
        urlImg: "https://media-cdn.tripadvisor.com/media/photo-s/0e/0c/df/11/fajitas-mixtas.jpg",
    },
    {
        id:38,
        cat:3,
        name: "Hamburguesa regular",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$8.00",
        urlImg: "https://m.ftscrt.com/food/621d9eb5-6466-45ab-aa9c-9039146637f4_lg_sq.jpg",
    },
    {
        id:39,
        cat:3,
        name: "Hamburguesa Doble carne",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$9.00",
        urlImg: "https://static.wixstatic.com/media/29cc8e_d71742bc6ab84e769b4937b344c72ebd~mv2.jpg/v1/fill/w_568,h_320,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/29cc8e_d71742bc6ab84e769b4937b344c72ebd~mv2.jpg",
    },
    {
        id:40,
        cat:3,
        name: "Hamburguesa Especial",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.00",
        urlImg: "https://resizer.glanacion.com/resizer/v2/hamburguesa-blt-de-john-john-burger-bacon-lettuce-RHVGX3MHVRB7VGEXBEVCCZHW5I.jpg?auth=53776ee5a203ae1fbe457df3473f7c2d9470016ad51a458c73c5b950966a4f57&width=768&quality=70&smart=false",
    },
    {
        id:41,
        cat:3,
        name: "Nuggets",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$8.99",
        urlImg: "https://westcofoods.com/wp-content/uploads/2020/09/Chicken-nuggets-7.jpg",
    },
    {
        id:42,
        cat:4,
        name: "Agua fresca - mediana",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$3.00",
        urlImg: "https://www.clarin.com/2020/07/21/7Pj44-Cyq_600x600__1.jpg",
    },
    {
        id:43,
        cat:4,
        name: "Agua fresca - grande",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$4.00",
        urlImg: "https://www.clarin.com/2020/07/21/7Pj44-Cyq_600x600__1.jpg",
    },
    {
        id:44,
        cat:4,
        name: "Cerveza",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$5.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740804131/imagen_2025-02-28_214208369_voo8xd.png",
    },
    {
        id:45,
        cat:4,
        name: "Michelada",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$10.99",
        urlImg: "https://editorialtelevisa.brightspotcdn.com/dims4/default/b81b0c7/2147483647/strip/true/crop/672x672+261+0/resize/1000x1000!/quality/90/?url=https%3A%2F%2Fk2-prod-editorial-televisa.s3.us-east-1.amazonaws.com%2Fbrightspot%2Fcb%2F87%2F9cf368f04c538a56846d6705dfaa%2Fmichelada-cubana-receta-facil-y-rapida.jpg",
    },
    {
        id:46,
        cat:4,
        name: "Michelada loca",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$14.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740804007/imagen_2025-02-28_214003923_xe5ndp.png",
    },
    {
        id:47,
        cat:5,
        name: "Menudo mediano",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$12.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797956/imagen_2025-01-13_125232710_rd6nye.png",
    },
    {
        id:48,
        cat:5,
        name: "Menudo grande",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$14.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736797956/imagen_2025-01-13_125232710_rd6nye.png",
    },
    {
        id:49,
        cat:5,
        name: "Birria de chivo mediano",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$13.99",
        urlImg: "https://www.cocinavital.mx/wp-content/uploads/2017/09/Birria.jpg",
    },
    {
        id:50,
        cat:5,
        name: "Birria de chivo grande",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$15.99",
        urlImg: "https://www.cocinavital.mx/wp-content/uploads/2017/09/Birria.jpg",
    },
    {
        id:51,
        cat:1,
        name: "Vampiro",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$3.50",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1736971991/imagen_2025-01-15_131308144_r4q3bs.png",
    },    
    {
        id:52,
        cat:2,
        name: "Camarones rellenos",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740803499/imagen_2025-02-28_213136495_hqrgil.png",
    },
    {
        id:53,
        cat:2,
        name: "Molcajete de mariscos",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$35.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740803555/imagen_2025-02-28_213232637_mrldyq.png",
    },
    {
        id:54,
        cat:2,
        name: "Camarones a la Luisiana",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$36.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740803590/imagen_2025-02-28_213307806_xawura.png",
    },
    {
        id:55,
        cat:2,
        name: "Empanadas de camaron 6 Pz",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$16.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740803773/imagen_2025-02-28_213610107_lz96ap.png",
    },
    {
        id:56,
        cat:2,
        name: "Aguachile mixto",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$23.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740803671/imagen_2025-02-28_213428107_lftmvz.png",
    },
    {
        id:57,
        cat:2,
        name: "Campechana",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel odio et mi lacinia scelerisque.",
        price: "$19.99",
        urlImg: "https://res.cloudinary.com/do5dkuplw/image/upload/v1740814183/1ebb4548-c930-4a90-b3de-5e8516ef0cf0_ptg5pc.jpg",
    },
]

export default MenuData;